# User=tokiodreamy-wix-twitch-integration

SSH_KEY="LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBdmV3emh1dVhXK010c1dIMFQ1MzFkS0JVQkFXZUNUekZINHE0TysxeTRBckE5cjFsCmRWVVlOU3FOUjBBcm9sZmJpL2R0Y1Qyc25CL3lTSURCVGoyazZtMDlCMDJnRkZRNFRLOVdBd0cwcFdZN2JCK2gKeXdmcWN5YkhpM0U0UDNJTUlBYjZ2LzJLYXhBQUgrOWNGVFA0WFoycWVuMzFlckRZUWMvTWM4SjZjbDc1TU9KWQpaL0hBa2JlOTczQ0Y3d1pENVkxNVRZYVZMU3J4SkJSUUFjbDV1V3h0OXJFdUgyQXFWMU93S3NUbTFZU0txdjAvCnVTYjhxUDRHQXNzRHBrQXRuZEQ3N0pEZ3RSb2o3NU43UFlCaVJESituTzVNZUVvRTh2V2lmclRhdkxmaWJJQkUKZml5Tk0xSDR6NS9aSXJyM29nZEhONmZIbU9Pc3ZJTGxjRXpJRndJREFRQUJBb0lCQVFDOUd2NG5YbGRrWit6cwpUVk45SHhQekgxem9jRXR1ZVRMeCtDYi9qS3V3UnlUaHlhM0hTWWFFRWEyQWYzV3kvUFlmQkt2VmNJcDVIaG9aCmRSS0UvRDVFS2FiMXFhWTE5N0hqTVVaY1VndDBFVG9qcTg5bW9LZ2lKai9VS1ZUUFg1aVJIMEgzZnRXZlN0eEUKOEFscEYwazZ0YTIwcjh5SWNLT3p5OXVRZTlsK0hEZ0JwTVNrMFNZSHRpdElna09MWm9uWFFhdlBQYkR3Zk9SQgpzcW9zaHZ3RU1BS2pLanNwT0NKTTIvUFBldEt2R253R1V1V0FiaUF6TTZxRkZXa0ozeVlKYlFuWDhRbk8xRy9HCm5BOFZLN21RYTFRbURkUC94bVNCYVdXbW5sLzM5RWpMREtUOG1rekNnNjhvVS85V2RxV0I5SHlEZE1mdlZkYXoKY2pBbE14MzVBb0dCQVBEaDE5dEI0YjYrdE1nL2grT1hVUjNxc0NHVFpTYzRoN3BvMXNTaDgzYjdnYVBLYzVqYwpCNWx4OEpFcVJuMVpCdzNEZUdxMzRGQy9rYTcveTQrVytzTDF2bjVXNXBKRDB1TUQ4QzhDa1paQ0lYYXVwVmx3CnZiY3M4dzAzNitNRnNsbGxjMFAvUFBUMHdJSFRUU3k3UTl1cXBRWEJxQ2ZCN1JxQXRkaVJPVktiQW9HQkFNblgKbko5RDdQNkxqVktSTGx2U292L1JMaE5IRmFYWHpidW9qeDRLb2xSNGRJU0duZXF0cHZWc3ZYQjRmSDAyTnk2YQp3NmtremdyZlZHVUJtLy9GV0JVOHZKa0kwTkgzeDZVK3RxYklHUENJQXlva2RHNjBzdmp3RmQxZzZaNzRSK29rClVLL0JEK1JWUmZGcXNxd2Nyd3BqZk94RGlmRkdPKzlWdFptS0YrbzFBb0dBUVk5bVBaR3Z6RWVCVXFNZjdBeXEKRWpkbTJxeVFNbDJMYTJ2UFVGTTN2V0YwaGt5NnE1YnZKbzlCUjNFM0lEU1QyK1lncHdNR3RWTitaaC9PbW5VZwpLT0hUaC9WRTZmZzF0SDNFNkRhTncxU2FZUC9sbHZNOVgxYUhqRWgxRmlQZHg4RDUzejdmcTFmVjhUKytXSGRiClg3VVJGd0QvTUZyeW1tei9rVUx0VkJNQ2dZRUF4dElvYVluVGJYbXhuOTk2dHVCcHgyd1o0c3RtdTVJMENlSWoKK0FlcGwyT0FBdnRIbXQrclVwM21qVjloNFVVQ1hsbjgyaVJ6QWFxenl6c21tMitkTUc0L3FNOVNRMEc3Mno1SApWVXBOcHNHVHZITmtiWmg1bzFWN2RESCticVZLMFkwc0hiUWpIMXdRSlpwZ25jRXpleHc4OWM0aGx4VUQvT0dFCm5OVzJjUEVDZ1lCQ2YzSnV1WkFaV0RXQ01WTWhUUWtMMlZLd1RSdWFhKzBLYWRpWGp2VU5qeG9yOEgwVDZHd1IKVGhXeTdHNnhuYm1VN242YTYvYk1wZlZuTEJZSW13WEZNUnBWR2h4ZVluVWRPTGhUQUlBZmtvQkYzL3diTnVoYQppQVgyMDl0dVc0YVQrZ3FjdG9oZVluYTJrb2wvQ2RiYTIranRFdUlQT3FjV284WEJUalU1Zmc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQ=="

# write the private key to a file (env var is base64 encoded with no line breaks (thanks circleci))
echo $SSH_KEY | base64 -d >key.pem
sudo chmod 600 key.pem

# copy built server binary to the ec2 instance
scp -o StrictHostKeyChecking=no -i key.pem target/release/server ubuntu@ec2-18-212-208-3.compute-1.amazonaws.com:/home/ubuntu/tokiodreamy-wix-twitch-integration-server

# enter the instance
ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@ec2-18-212-208-3.compute-1.amazonaws.com <<-'SSH_EOF'
	# stop the service
	sudo systemctl stop tokiodreamy-wix-twitch-integration-server

	# move the new binary, overwriting the old one
	sudo mv tokiodreamy-wix-twitch-integration-server /usr/local/bin/tokiodreamy-wix-twitch-integration-server

	sudo cat <<EOF >tokiodreamy-wix-twitch-integration-server.service
	[Unit]
	Description=Tokiodreamy Wix/Twitch Integration Server
	After=network.target
	StartLimitIntervalSec=0
	[Service]
	Type=simple
	Restart=always
	RestartSec=1
	ExecStart=/usr/local/bin/tokiodreamy-wix-twitch-integration-server --dotenv-file-path /home/ubuntu/.env
	[Install]
	WantedBy=multi-user.target
	EOF

	sudo mv tokiodreamy-wix-twitch-integration-server.service /etc/systemd/system/tokiodreamy-wix-twitch-integration-server.service

	sudo systemctl daemon-reload

	# restart the service
	sudo systemctl enable tokiodreamy-wix-twitch-integration-server
	sudo systemctl start tokiodreamy-wix-twitch-integration-server
	sudo systemctl status tokiodreamy-wix-twitch-integration-server
SSH_EOF
