version: 2.1

jobs:
  test:
    docker:
      - image: cimg/rust:1.67.0
    steps:
      - checkout
      - run:
          name: "Test workspace"
          command: "cargo test --workspace"

  build:
    docker:
      - image: cimg/rust:1.67.0
    steps:
      - checkout
      - run:
          name: "Build server"
          command: "cargo build --release"
      - persist_to_workspace:
          root: target/release
          paths:
            - server

  deploy:
    # docker:
    #   - image: cimg/rust:1.67.0
    machine:
      enabled: true
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: target/release
      - run:
          name: Deploy Over SSH
          command: |
            # write the private key to a file (env var is base64 encoded with no line breaks (thanks circleci))
            echo $SSH_KEY | base64 -d >key.pem
            chmod 600 key.pem

            # copy built server binary to the ec2 instance
            scp -o StrictHostKeyChecking=no \
            	-i key.pem target/release/server \
            	${SSH_USER}@${SSH_HOST}:/home/ubuntu/tokiodreamy-wix-twitch-integration-server

            # enter the instance
            ssh -o StrictHostKeyChecking=no -i key.pem ${SSH_USER}@${SSH_HOST} <<-'SSH_EOF'
            	# stop the service
            	sudo systemctl stop tokiodreamy-wix-twitch-integration-server

            	# move the new binary, overwriting the old one
            	sudo mv tokiodreamy-wix-twitch-integration-server /usr/local/bin/tokiodreamy-wix-twitch-integration-server

            	sudo cat <<EOF >tokiodreamy-wix-twitch-integration-server.service
            	[Unit]
            	Description=Tokiodreamy Wix/Twitch Integration Server
            	After=network.target
            	StartLimitIntervalSec=0
            	[Service]
            	Type=simple
            	Restart=always
            	RestartSec=1
            	ExecStart=/usr/local/bin/tokiodreamy-wix-twitch-integration-server --dotenv-file-path /home/ubuntu/.env
            	[Install]
            	WantedBy=multi-user.target
            	EOF

            	sudo mv tokiodreamy-wix-twitch-integration-server.service /etc/systemd/system/tokiodreamy-wix-twitch-integration-server.service

            	sudo systemctl daemon-reload

            	# restart the service
            	sudo systemctl enable tokiodreamy-wix-twitch-integration-server
            	sudo systemctl start tokiodreamy-wix-twitch-integration-server
            	sudo systemctl status tokiodreamy-wix-twitch-integration-server
            SSH_EOF
            ssh $SSH_USER@$SSH_HOST "<remote deploy command>"

workflows:
  build-and-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
          branches:
            only: main
